=== keatsig/PowerModelsONM.jl/schemas/input-settings.schema.json
{
  "meta:license": [
    "Copyright (c) 2020, Triad National Security, LLC.",
    "This code is provided under a BSD license as part of the Multi-Infrastructure Control",
    "and Optimization Toolkit (MICOT) project, LA-CC-13-108.",
    "You may not use this file except in compliance with the License. You may obtain a copy",
    "of the License at https://github.com/lanl-ansi/PowerModelsONM.jl/blob/main/LICENSE.md"
  ],
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "schemas/settings",
  "type": "object",
  "title": "Settings",
  "additionalProperties": false,
  "description": "Network settings to apply to the base network (_i.e._, all multinetwork timesteps, not a specific one), such as bus voltage bounds, load priorities, cold load pickup, and global settings such as maximum switch actions per timestep and time elapsed per time step.\n\n Additional properties on each object are allowed, but the object types are restricted to those in the ONM model.",
  "x-tags": ["input"],
  "examples": [
    {
      "max_switch_actions": [1, 1, 1],
      "time_elapsed": [0.1667, 0.1667, 0.1667],
      "load": {
        "671": {
          "clpu_factor": 2
        }
      }
    }
  ],
  "properties": {
    "settings": {
      "$ref": "./settings/input-settings-settings.schema.json"
    },
    "generator": {
      "$ref": "./settings/input-settings-generator.schema.json"
    },
    "solar": {
      "$ref": "./settings/input-settings-solar.schema.json"
    },
    "voltage_source": {
      "$ref": "./output-optimization_metadata.schema.json"
    },
    "storage": {
      "$ref": "./settings/input-settings-storage.schema.json"
    },
    "bus": {
      "$ref": "./settings/input-settings-bus.schema.json"
    },
    "load": {
      "$ref": "./settings/input-settings-load.schema.json"
    },
    "shunt": {
      "$ref": "./settings/input-settings-shunt.schema.json"
    },
    "line": {
      "$ref": "./settings/input-settings-line.schema.json"
    },
    "switch": {
      "$ref": "./settings/input-settings-switch.schema.json"
    },
    "transformer": {
      "$ref": "./settings/input-settings-transformer.schema.json"
    },
    "max_switch_actions": {
      "type": ["array", "number"],
      "description": "The maximum allowed switching actions per timestep (or at each timestep, if an array)",
      "items": {
        "type": "number"
      }
    },
    "disable_networking": {
      "type": ["boolean"],
      "description": "Disables microgrid networking"
    },
    "disable_radial_constraint": {
      "type": ["boolean"],
      "description": "Disables radiality constraints"
    },
    "disable_isolation_constraint": {
      "type": ["boolean"],
      "description": "Disables block isolation constraint"
    },
    "disable_inverter_constraint": {
      "type": ["boolean"],
      "description": "Disables constraint that enforces only one grid-forming inverter per connected component (might cause issues with Cbc)"
    },
    "disable_switch_penalty": {
      "type": ["boolean"],
      "description": "apply penalty to switching in objective"
    },
    "apply_switch_scores": {
      "type": ["boolean"],
      "description": "apply weight to switches in objective"
    },
    "disable_presolver": {
      "type": ["boolean"],
      "description": "disables presolvers on included solvers that support it (Gurobi, KNITRO)",
      "default": false
    },
    "time_elapsed": {
      "type": ["array", "number"],
      "description": "The time elapsed, in hours for each timestep, or individually after each timestep if an array",
      "items": {
        "type": "number"
      }
    },
    "nlp_solver_tol": {
      "type": "number",
      "description": "The tolerance of the nlp solver"
    },
    "mip_solver_tol": {
      "type": "number",
      "description": "The tolerance of the mip solver"
    },
    "mip_solver_gap": {
      "type": "number",
      "exclusiveMinimum": 0,
      "default": 0.05,
      "format": "float",
      "description": "MIP Gap for MIP/MISOCP solvers"
    }
  }
}

=== keatsig/PowerModelsONM.jl/test/data/ieee13_settings.json
{
  "voltage_source": {
    "source": { "pg_lb": [0.0, 0.0, 0.0], "qg_lb": [0.0, 0.0, 0.0] }
  },
  "line": {
    "632670": {
      "vad_ub": [5.0, 5.0, 5.0],
      "cm_ub": [null, null, null],
      "vad_lb": [-5.0, -5.0, -5.0]
    },
    "700701": {
      "vad_ub": [5.0, 5.0, 5.0],
      "cm_ub": [null, null, null],
      "vad_lb": [-5.0, -5.0, -5.0]
    },
    "632645": {
      "vad_ub": [5.0, 5.0],
      "cm_ub": [null, null],
      "vad_lb": [-5.0, -5.0]
    },
    "684611": { "vad_ub": [5.0], "cm_ub": [null], "vad_lb": [-5.0] },
    "692675": {
      "vad_ub": [5.0, 5.0, 5.0],
      "cm_ub": [null, null, null],
      "vad_lb": [-5.0, -5.0, -5.0]
    },
    "675675aux": {
      "vad_ub": [5.0, 5.0, 5.0],
      "cm_ub": [null, null, null],
      "vad_lb": [-5.0, -5.0, -5.0]
    },
    "671684": {
      "vad_ub": [5.0, 5.0],
      "cm_ub": [null, null],
      "vad_lb": [-5.0, -5.0]
    },
    "645646": {
      "vad_ub": [5.0, 5.0],
      "cm_ub": [null, null],
      "vad_lb": [-5.0, -5.0]
    },
    "650632": {
      "vad_ub": [5.0, 5.0, 5.0],
      "cm_ub": [null, null, null],
      "vad_lb": [-5.0, -5.0, -5.0]
    },
    "702703": {
      "vad_ub": [5.0, 5.0, 5.0],
      "cm_ub": [null, null, null],
      "vad_lb": [-5.0, -5.0, -5.0]
    },
    "671680": {
      "vad_ub": [5.0, 5.0, 5.0],
      "cm_ub": [null, null, null],
      "vad_lb": [-5.0, -5.0, -5.0]
    },
    "632633": {
      "vad_ub": [5.0, 5.0, 5.0],
      "cm_ub": [null, null, null],
      "vad_lb": [-5.0, -5.0, -5.0]
    },
    "684652": { "vad_ub": [5.0], "cm_ub": [null], "vad_lb": [-5.0] },
    "670671": {
      "vad_ub": [5.0, 5.0, 5.0],
      "cm_ub": [null, null, null],
      "vad_lb": [-5.0, -5.0, -5.0]
    }
  },
  "bus": {
    "671": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959]
    },
    "800": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959]
    },
    "680": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959]
    },
    "634": {
      "vm_ub": [0.30484094213212237, 0.30484094213212237, 0.30484094213212237],
      "vm_lb": [0.24941531628991828, 0.24941531628991828, 0.24941531628991828]
    },
    "652": { "vm_ub": [2.641954831811728], "vm_lb": [2.161599407845959] },
    "701": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959],
      "microgrid_id": "3"
    },
    "675": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959],
      "microgrid_id": "2"
    },
    "702": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959],
      "microgrid_id": "4"
    },
    "650": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959]
    },
    "700": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959],
      "microgrid_id": "3"
    },
    "801": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959],
      "microgrid_id": "1"
    },
    "rg60": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959]
    },
    "611": { "vm_ub": [2.641954831811728], "vm_lb": [2.161599407845959] },
    "645": {
      "vm_ub": [2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959]
    },
    "632": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959]
    },
    "675aux": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959],
      "microgrid_id": "2"
    },
    "703": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959],
      "microgrid_id": "4"
    },
    "633": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959]
    },
    "684": {
      "vm_ub": [2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959]
    },
    "692": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959],
      "microgrid_id": "2"
    },
    "670": {
      "vm_ub": [2.641954831811728, 2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959, 2.161599407845959]
    },
    "646": {
      "vm_ub": [2.641954831811728, 2.641954831811728],
      "vm_lb": [2.161599407845959, 2.161599407845959]
    }
  },
  "nlp_solver_tol": 0.0001,
  "mip_solver_tol": 0.0001,
  "mip_solver_gap": 0.05,
  "settings": { "sbase_default": 1000.0 },
  "transformer": {
    "xfm1": { "sm_ub": null },
    "reg1": { "sm_ub": null },
    "sub": { "sm_ub": null }
  },
  "shunt": {},
  "solar": {},
  "storage": {
    "Battery_mg1a": { "phase_unbalance_factor": 0.0 },
    "Battery_mg1b": { "phase_unbalance_factor": 0.0 },
    "Battery_mg1c": { "phase_unbalance_factor": 0.0 }
  },
  "switch": {
    "801675": { "cm_ub": [25.0, 25.0, 25.0] },
    "671692": { "cm_ub": [null, null, null] },
    "671700": { "cm_ub": [null, null, null] },
    "703800": { "cm_ub": [null, null, null] },
    "800801": { "cm_ub": [25.0, 25.0, 25.0] },
    "701702": { "cm_ub": [null, null, null] }
  },
  "generator": {},
  "load": {
    "671_1": { "clpu_factor": 2.0 },
    "634a": { "clpu_factor": 2.0 },
    "692_3": { "clpu_factor": 2.0 },
    "675b": { "clpu_factor": 2.0 },
    "675a": { "clpu_factor": 2.0 },
    "652": { "clpu_factor": 2.0 },
    "692_1": { "clpu_factor": 2.0 },
    "701": { "clpu_factor": 2.0 },
    "671_3": { "clpu_factor": 2.0 },
    "702": { "clpu_factor": 2.0 },
    "646_3": { "clpu_factor": 2.0 },
    "700": { "clpu_factor": 2.0 },
    "801": { "clpu_factor": 2.0 },
    "670c": { "clpu_factor": 2.0 },
    "611": { "clpu_factor": 2.0 },
    "645": { "clpu_factor": 2.0 },
    "634c": { "clpu_factor": 2.0 },
    "671_2": { "clpu_factor": 2.0 },
    "703": { "clpu_factor": 2.0 },
    "670b": { "clpu_factor": 2.0 },
    "634b": { "clpu_factor": 2.0 },
    "675c": { "clpu_factor": 2.0 },
    "670a": { "clpu_factor": 2.0 },
    "646_2": { "clpu_factor": 2.0 }
  },
  "max_switch_actions": [1, 1, 1, 1, 1, 1, 1, 1],
  "disable_switch_penalty": false,
  "apply_switch_scores": true,
  "disable_presolver": true
}
